# Generated by Django 4.0.6 on 2022-07-22 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 22, 13, 37, 39, 155850, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
